/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.bases;

import java.sql.*;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import javax.swing.table.TableModel;

/**
 *
 * @author b22539
 */
public class Administrador extends javax.swing.JFrame {
    private Object[][] tuplaCliente = new Object[0][0];
    private Object[][] tuplaProducto = new Object[0][0];
    private Object[][] tuplaVendedor = new Object[0][0];
    private Object[][] tuplaVenta = new Object[0][0];
    private Object[][] tuplaProveedor = new Object[0][0];
    private String conexion;
    private int filasCliente;
    private int filasProducto;
    private int filasVendedor;
    private int filasVenta;
    private int filasProveedor;
    private TableRowSorter<TableModel> sorter;

    /**
     * Creates new form NewJFrame
     */
    public Administrador(String conexion) {
        this.conexion = conexion;
        initComponents();
        cargar(tablaProveedor, "PROVEEDOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        agregarCliente = new javax.swing.JButton();
        actualizarCliente = new javax.swing.JButton();
        eliminarCliente = new javax.swing.JButton();
        consultaCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        empleado = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        agregarProducto = new javax.swing.JButton();
        actualizarProducto = new javax.swing.JButton();
        eliminarProducto = new javax.swing.JButton();
        consultaProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();
        agregarVendedor = new javax.swing.JButton();
        actualizarVendedor = new javax.swing.JButton();
        consultaVendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        actualizarVenta = new javax.swing.JButton();
        eliminarVenta = new javax.swing.JButton();
        consultaVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        agregarProveedor = new javax.swing.JButton();
        actualizarProveedor = new javax.swing.JButton();
        eliminarProveedor = new javax.swing.JButton();
        consultaProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton8.setText("Agregar");

        jButton9.setText("Actualizar");

        jButton10.setText("Eliminar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaClienteMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCliente);

        agregarCliente.setText("Agregar");
        agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarClienteActionPerformed(evt);
            }
        });

        actualizarCliente.setText("Actualizar");
        actualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarClienteActionPerformed(evt);
            }
        });

        eliminarCliente.setText("Eliminar");
        eliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarClienteActionPerformed(evt);
            }
        });

        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("Consulta:");

        empleado.setText("Empleados");
        empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(actualizarCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminarCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(empleado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(agregarCliente)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCliente)
                    .addComponent(actualizarCliente)
                    .addComponent(eliminarCliente)
                    .addComponent(empleado))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Clientes", jPanel3);

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaProductoMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tablaProducto);

        agregarProducto.setText("Agregar");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });

        actualizarProducto.setText("Actualizar");
        actualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProductoActionPerformed(evt);
            }
        });

        eliminarProducto.setText("Eliminar");
        eliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProductoActionPerformed(evt);
            }
        });

        consultaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaProductoActionPerformed(evt);
            }
        });

        jLabel3.setText("Consulta:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(actualizarProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminarProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarProducto)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarProducto)
                    .addComponent(actualizarProducto)
                    .addComponent(eliminarProducto))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Productos", jPanel4);

        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaVendedorMouseReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tablaVendedor);

        agregarVendedor.setText("Agregar");
        agregarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarVendedorActionPerformed(evt);
            }
        });

        actualizarVendedor.setText("Actualizar");
        actualizarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarVendedorActionPerformed(evt);
            }
        });

        consultaVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaVendedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Consulta:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(actualizarVendedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarVendedor)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarVendedor)
                    .addComponent(actualizarVendedor))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Vendedor", jPanel6);

        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaVentaMouseReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tablaVenta);

        actualizarVenta.setText("Actualizar");
        actualizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarVentaActionPerformed(evt);
            }
        });

        eliminarVenta.setText("Eliminar");
        eliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarVentaActionPerformed(evt);
            }
        });

        consultaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaVentaActionPerformed(evt);
            }
        });

        jLabel5.setText("Consulta:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                            .addComponent(actualizarVenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminarVenta)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarVenta)
                    .addComponent(eliminarVenta))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Venta", jPanel7);

        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaProveedorMouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tablaProveedor);

        agregarProveedor.setText("Agregar");
        agregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProveedorActionPerformed(evt);
            }
        });

        actualizarProveedor.setText("Actualizar");
        actualizarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProveedorActionPerformed(evt);
            }
        });

        eliminarProveedor.setText("Eliminar");
        eliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProveedorActionPerformed(evt);
            }
        });

        consultaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaProveedorActionPerformed(evt);
            }
        });

        jLabel1.setText("Consulta:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(actualizarProveedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminarProveedor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agregarProveedor)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarProveedor)
                    .addComponent(actualizarProveedor)
                    .addComponent(eliminarProveedor))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Proveedores", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void eliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarVentaActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere eliminar estas ventas?") == 0) {
            for(int i = 0; i < tuplaVenta.length; i++){
                String query = "DELETE FROM VENTA WHERE IDVENDEDOR = ? AND NUMERODEVENTA = ? AND"
                    + " IDCLIENTE = ? AND FORMADEPAGO = ? AND FECHAVENTA = ? AND COSTOTOTAL = ? AND PAGOTOTAL = ?";
                TablaDatos.executeUpdate(conexion, query, tuplaVenta[i]);
            }
            cargar(tablaVenta, "VENTA");
        }
    }//GEN-LAST:event_eliminarVentaActionPerformed

    private void eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProductoActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere eliminar a estos productos?") == 0) {
            for(int i = 0; i < tuplaProducto.length; i++){
                String query = "DELETE FROM PRODUCTO WHERE NOMBREPROVEEDOR = ? AND NOMBREPRODUCTO = ? AND"
                    + " MARCAPRODUCTO = ? AND ESTANTE = ? AND CODIGODEFABRICA = ? AND EXISTENCIA = ? AND PRECIOVENTA = ? AND" 
                    + "COSTOUNIDAD = ?";
                TablaDatos.executeUpdate(conexion, query, tuplaProducto[i]);
            }
            cargar(tablaProducto, "PRODUCTO");
        }
    }//GEN-LAST:event_eliminarProductoActionPerformed

    private void eliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarClienteActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere eliminar a estos clientes?") == 0) {
            for(int i = 0; i < tuplaCliente.length; i++){
                String query = "DELETE FROM CLIENTE WHERE IDCLIENTE = ? AND PRIORIDADCLIENTE = ? AND NOMBRECLIENTE = ?";
                TablaDatos.executeUpdate(conexion, query, tuplaCliente[i]);
            }
            cargar(tablaCliente, "Cliente");
        }
    }//GEN-LAST:event_eliminarClienteActionPerformed

    private void eliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProveedorActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Está seguro de que quiere eliminar a estos proveedores?") == 0) {
            for(int i = 0; i < tuplaProveedor.length; i++){
                String query = "DELETE FROM PROVEEDOR WHERE NOMBREPROVEEDOR = ? AND TELEFONOPROVEEDOR = ? AND CORREOPROVEEDOR = ?";
                TablaDatos.executeUpdate(conexion, query, tuplaProveedor[i]);
            }
            cargar(tablaProveedor, "PROVEEDOR");
        }
    }//GEN-LAST:event_eliminarProveedorActionPerformed

    private void consultaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaProveedorActionPerformed
        filtrar(consultaProveedor);
    }//GEN-LAST:event_consultaProveedorActionPerformed

    private void consultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteActionPerformed
        filtrar(consultaCliente);
    }//GEN-LAST:event_consultaClienteActionPerformed

    private void consultaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaProductoActionPerformed
        filtrar(consultaProducto);
    }//GEN-LAST:event_consultaProductoActionPerformed

    private void consultaVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaVendedorActionPerformed
        filtrar(consultaVendedor);
    }//GEN-LAST:event_consultaVendedorActionPerformed

    private void consultaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaVentaActionPerformed
        filtrar(consultaVenta);
    }//GEN-LAST:event_consultaVentaActionPerformed

    private void agregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProveedorActionPerformed
        ModificarProveedor prov = new ModificarProveedor(conexion,true,()->{cargar(tablaProveedor, "PROVEEDOR");}, tuplaProveedor);
        prov.setVisible(true);
    }//GEN-LAST:event_agregarProveedorActionPerformed

    private void actualizarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProveedorActionPerformed
        ModificarProveedor prov = new ModificarProveedor(conexion,false,()->{cargar(tablaProveedor, "PROVEEDOR");}, tuplaProveedor);
        prov.setVisible(true);
    }//GEN-LAST:event_actualizarProveedorActionPerformed

    private void tablaProveedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProveedorMouseReleased
        int[] row = tablaProveedor.getSelectedRows();
        filasProveedor = row.length;
        tuplaProveedor = new String[filasProveedor][3];
        for(int i = 0; i < filasProveedor; i++){
            for(int j = 0; j < 3; j++){
                tuplaProveedor[i][j] = tablaProveedor.getValueAt(row[i], j);
            } 
        }
    }//GEN-LAST:event_tablaProveedorMouseReleased

    private void tablaVentaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentaMouseReleased
        int[] row = tablaVenta.getSelectedRows();
        filasVenta = row.length;
        tuplaVenta = new String[filasVenta][7];
        for(int i = 0; i < filasVenta; i++){
            for(int j = 0; j < 7; j++){
                tuplaVenta[i][j] = tablaVenta.getValueAt(row[i], j);
            } 
        }
    }//GEN-LAST:event_tablaVentaMouseReleased

    private void tablaVendedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVendedorMouseReleased
        int[] row = tablaVendedor.getSelectedRows();
        filasVendedor = row.length;
        tuplaVendedor = new String[filasVendedor][2];
        for(int i = 0; i < filasVendedor; i++){
            for(int j = 0; j < 2; j++){
                tuplaVendedor[i][j] = tablaVendedor.getValueAt(row[i], j);
            } 
        }
    }//GEN-LAST:event_tablaVendedorMouseReleased

    private void tablaProductoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductoMouseReleased
        int[] row = tablaProducto.getSelectedRows();
        filasProducto = row.length;
        tuplaProducto = new String[filasProducto][8];
        for(int i = 0; i < filasProducto; i++){
            for(int j = 0; j < 8; j++){
                tuplaProducto[i][j] = tablaProducto.getValueAt(row[i], j);
            } 
        }
    }//GEN-LAST:event_tablaProductoMouseReleased

    private void tablaClienteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMouseReleased
        int[] row = tablaCliente.getSelectedRows();
        filasCliente = row.length;
        tuplaCliente = new String[filasCliente][3];
        for(int i = 0; i < filasCliente; i++){
            for(int j = 0; j < 3; j++){
                tuplaCliente[i][j] = tablaCliente.getValueAt(row[i], j);
            } 
        }   
    }//GEN-LAST:event_tablaClienteMouseReleased

    private void agregarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarVendedorActionPerformed
        ModificarVendedor vende = new ModificarVendedor(conexion,true,()->{cargar(tablaVendedor, "VENDEDOR");}, tuplaProveedor);
        vende.setVisible(true);
    }//GEN-LAST:event_agregarVendedorActionPerformed

    private void actualizarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarVendedorActionPerformed
        ModificarVendedor vende = new ModificarVendedor(conexion,false,()->{cargar(tablaProveedor, "PROVEEDOR");}, tuplaProveedor);
        vende.setVisible(true);
    }//GEN-LAST:event_actualizarVendedorActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        ModificarProducto prod = new ModificarProducto(conexion,true,()->{cargar(tablaProducto, "PRODUCTO");}, tuplaProducto);
        prod.setVisible(true);
    }//GEN-LAST:event_agregarProductoActionPerformed

    private void agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarClienteActionPerformed
        ModificarClienteAdmin client = new ModificarClienteAdmin(conexion,true,()->{cargar(tablaCliente, "ClIENTE");}, tuplaProducto);
        client.setVisible(true);
    }//GEN-LAST:event_agregarClienteActionPerformed

    private void actualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProductoActionPerformed
        ModificarProducto prod = new ModificarProducto(conexion,false,()->{cargar(tablaProducto, "PRODUCTO");}, tuplaProducto);
        prod.setVisible(true);
    }//GEN-LAST:event_actualizarProductoActionPerformed

    private void actualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarClienteActionPerformed
        ModificarClienteAdmin client = new ModificarClienteAdmin(conexion,false,()->{cargar(tablaCliente, "ClIENTE");}, tuplaProducto);
        client.setVisible(true);
    }//GEN-LAST:event_actualizarClienteActionPerformed

    private void actualizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarVentaActionPerformed
        ModificarVenta venta = new ModificarVenta(conexion,()->{cargar(tablaVenta, "VENTA");}, tuplaVenta);
        venta.setVisible(true);
    }//GEN-LAST:event_actualizarVentaActionPerformed

    private void empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empleadoActionPerformed
        BorrarEmpleados empleados = new BorrarEmpleados(conexion,tuplaCliente);
        empleados.setVisible(true);
    }//GEN-LAST:event_empleadoActionPerformed

    private void cargar(JTable tipo, String tabla) {
        String consulta = "SELECT * FROM DBO." + tabla; 
        ResultSet rs = TablaDatos.executeQuery(conexion, consulta, new Object[0]);
        try{
        tipo.setModel(TablaDatos.buildTableModel(rs));
        sorter = new TableRowSorter<>(TablaDatos.buildTableModel(rs));
        tipo.setRowSorter(sorter);
        }catch(Exception e){
            System.err.println("No se encontro tabla");
        }
        tipo.setEnabled(tipo.getSelectedRowCount() == 0);
        //boton.setEnabled(tipo.getSelectedRowCount() != 0);
    }
    
    private void filtrar(JTextField filterText){
        String text = filterText.getText();
        if (text.length() == 0) {
          sorter.setRowFilter(null);
        } else {
          sorter.setRowFilter(RowFilter.regexFilter(text));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarCliente;
    private javax.swing.JButton actualizarProducto;
    private javax.swing.JButton actualizarProveedor;
    private javax.swing.JButton actualizarVendedor;
    private javax.swing.JButton actualizarVenta;
    private javax.swing.JButton agregarCliente;
    private javax.swing.JButton agregarProducto;
    private javax.swing.JButton agregarProveedor;
    private javax.swing.JButton agregarVendedor;
    private javax.swing.JTextField consultaCliente;
    private javax.swing.JTextField consultaProducto;
    private javax.swing.JTextField consultaProveedor;
    private javax.swing.JTextField consultaVendedor;
    private javax.swing.JTextField consultaVenta;
    private javax.swing.JButton eliminarCliente;
    private javax.swing.JButton eliminarProducto;
    private javax.swing.JButton eliminarProveedor;
    private javax.swing.JButton eliminarVenta;
    private javax.swing.JButton empleado;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaProducto;
    private javax.swing.JTable tablaProveedor;
    private javax.swing.JTable tablaVendedor;
    private javax.swing.JTable tablaVenta;
    // End of variables declaration//GEN-END:variables
}
