/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.bases;

import java.sql.*;
import javax.swing.*;
import java.util.Collections;
/**
 *
 * @author b22539
 */
public class ModificarProducto extends javax.swing.JFrame {
    private String conexion;
    private boolean type;
    final Runnable function;
    private String llaveProveedor;
    private String llaveNombre;
    private String llaveMarca;

    /**
     * Creates new form NewJFrame
     */
    public ModificarProducto(String conexion, boolean type, Runnable function, Object[][] nuevos) {
        this.function = function;
        this.conexion = conexion;
        this.type = type;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        if(!type){
            llaveProveedor = nuevos[0][0].toString();
            llaveNombre = nuevos[0][1].toString();
            llaveMarca = nuevos[0][2].toString();
            proveedor.setText(nuevos[0][0].toString());
            nombre.setText(nuevos[0][1].toString());
            marca.setText(nuevos[0][2].toString());
            estante.setText(nuevos[0][3].toString());
            codigo.setText(nuevos[0][4].toString());
            existencia.setText(nuevos[0][5].toString());
            precio.setText(nuevos[0][6].toString());
            costo.setText(nuevos[0][7].toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        proveedor = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        estante = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        existencia = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Proveedor:");

        jLabel2.setText("Marca:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Estante:");

        jLabel5.setText("Código:");

        jLabel6.setText("Existencia:");

        jLabel7.setText("Precio:");

        jLabel8.setText("Costo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proveedor)
                            .addComponent(marca)
                            .addComponent(nombre)
                            .addComponent(estante)
                            .addComponent(codigo)
                            .addComponent(existencia)
                            .addComponent(precio)
                            .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(estante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(existencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresar)
                    .addComponent(aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if(type){
            Object[] atributos = new Object[8];
            atributos[0] = proveedor.getText();
            atributos[1] = nombre.getText();
            atributos[2] = marca.getText();
            atributos[3] = Integer.parseInt(estante.getText());
            atributos[4] = codigo.getText();
            atributos[5] = Integer.parseInt(existencia.getText());
            atributos[6] = Integer.parseInt(precio.getText());
            atributos[7] = Integer.parseInt(costo.getText());
            String query = "INSERT INTO DBO.PRODUCTO VALUES(?,?,?,?,?,?,?,?)";
            TablaDatos.executeUpdate(conexion, query, atributos);
        }else{
            Object[] atributos = new Object[11];
            atributos[0] = proveedor.getText();
            atributos[1] = nombre.getText();
            atributos[2] = marca.getText();
            atributos[3] = Integer.parseInt(estante.getText());
            atributos[4] = codigo.getText();
            atributos[5] = Integer.parseInt(existencia.getText());
            atributos[6] = Integer.parseInt(precio.getText());
            atributos[7] = Integer.parseInt(costo.getText());
            atributos[8] = llaveProveedor;
            atributos[9] = llaveNombre;
            atributos[10] = llaveMarca;
            String query = "UPDATE DBO.PRODUCTO SET NOMBREPROVEEDOR = ?, NOMBREPRODUCTO = ?,"
                    + " MARCAPRODUCTO = ?, ESTANTE = ?, CODIGODEFABRICA = ?, EXISTENCIA = ?, PRECIODEVENTA = ?," 
                    + "COSTOUNIDAD = ? WHERE NOMBREPROVEEDOR = ? AND NOMBREPRODUCTO = ? AND MARCAPRODUCTO = ?";
            TablaDatos.executeUpdate(conexion, query, atributos);
        }
        actualizar();
    }//GEN-LAST:event_aceptarActionPerformed

    private void actualizar() {
        try {
            function.run();
        } catch (Exception ex) {
            System.err.print("Error al retornar al padre");
        }
        this.dispose();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField costo;
    private javax.swing.JTextField estante;
    private javax.swing.JTextField existencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    private javax.swing.JTextField proveedor;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
