/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.bases;

import java.util.Collections;
import java.util.List;
import java.util.Vector;

/**
 *
 * @author b22539
 */
public class ModificarCliente extends javax.swing.JFrame {

    final Runnable functionOnClose;
    final boolean type;
    final String con;
    final String originalKey; 

    /**
     * Creates new form ModificarCliente
     */
    public ModificarCliente(String[] TextFieldValues, Runnable functionOnClose, boolean type, String con) {
        this.functionOnClose = functionOnClose;
        this.type = type;
        this.con = con;
        this.originalKey = TextFieldValues[0];
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        if (type) {
            modificar.setText("Agregar");
        } else {
            modificar.setText("Modificar");
            fieldNombre1.setText(TextFieldValues[2]);
            fieldIdentificacion.setText(TextFieldValues[0]);
            fieldPrioridad.setText(TextFieldValues[1]);
        }
    }

    public ModificarCliente(Runnable functionOnClose, boolean type, String con) {
        this(Collections.nCopies(3, "").toArray(new String[3]), functionOnClose, type, con);
    }

    public ModificarCliente(String[] TextFieldValues, boolean type, String con) {
        this(TextFieldValues, null, type, con);
    }

    public ModificarCliente(boolean type, String con) {
        this(Collections.nCopies(3, "").toArray(new String[7]), null, type, con);
    }

    private void returnToParent() {
        try {
            functionOnClose.run();
        } catch (Exception e) {
            System.err.print("Error al retornar al padre");
            e.printStackTrace();
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labe = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldIdentificacion = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        fieldPrioridad = new javax.swing.JTextField();
        labelIdentificacion = new javax.swing.JLabel();
        labelPrioridad = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        labe1 = new javax.swing.JLabel();
        fieldNombre1 = new javax.swing.JTextField();

        labe.setText("Nombre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        labelIdentificacion.setText("Identficación:");

        labelPrioridad.setText("Prioridad:");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        labe1.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(modificar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelPrioridad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labe1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNombre1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(fieldPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificacion)
                    .addComponent(fieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrioridad)
                    .addComponent(fieldPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(Regresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        
        if (type) {
            Object[] parameters = {fieldIdentificacion.getText().trim(),
            Integer.parseInt(fieldPrioridad.getText().trim()),
            fieldNombre1.getText().trim()};
            TablaDatos.executeUpdate(con, "Insert into dbo.cliente values (?,?,?)", parameters);
        } else {
            Object[] parameters = {fieldIdentificacion.getText().trim(),
            Integer.parseInt(fieldPrioridad.getText().trim()),
            fieldNombre1.getText().trim(),
            originalKey};
            TablaDatos.executeUpdate(con, "Update DBO.Cliente set IDCLIENTE = ?, PRIORIDADCLIENTE = ?, NOMBRECLIENTE = ? WHERE IDCLIENTE = ?", parameters);
        }
        returnToParent();
    }//GEN-LAST:event_modificarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        returnToParent();
    }//GEN-LAST:event_RegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField fieldIdentificacion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNombre1;
    private javax.swing.JTextField fieldPrioridad;
    private javax.swing.JLabel labe;
    private javax.swing.JLabel labe1;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelPrioridad;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
