/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.bases;

import java.sql.*;
import javax.swing.*;
import java.util.Collections;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author b22539
 */
public class ModificarVenta extends javax.swing.JFrame {
    private String conexion;
    final Runnable function;
    private String llaveVendedor;
    private String llaveNumero;
    /**
     * Creates new form NewJFrame
     */
    public ModificarVenta(String conexion, Runnable function, Object[][] nuevos) {
        this.function = function;
        this.conexion = conexion;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        llaveVendedor = nuevos[0][0].toString();
        llaveNumero = nuevos[0][1].toString();
        vendedor.setText(nuevos[0][0].toString());
        numero.setText(nuevos[0][1].toString());
        fecha.setText(nuevos[0][4].toString());
        forma.setText(nuevos[0][3].toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regresar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vendedor = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        fecha = new javax.swing.JTextField();
        forma = new javax.swing.JTextField();
        abonado = new javax.swing.JTextField();
        pendiente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Vendedor:");

        jLabel2.setText("Numero:");

        jLabel3.setText("Fecha:");

        jLabel4.setText("Forma de pago:");

        jLabel5.setText("Abonado:");

        jLabel6.setText("Pendiente:");

        forma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vendedor)
                            .addComponent(numero)
                            .addComponent(fecha)
                            .addComponent(forma)
                            .addComponent(abonado)
                            .addComponent(pendiente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(aceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(forma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(abonado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pendiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresar)
                    .addComponent(aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formaActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
       try{
        Object[] atributos = new Object[6];
        atributos[0] = vendedor.getText();
        atributos[1] = Integer.parseInt(numero.getText());
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        Date parsed = format.parse(fecha.getText());
        atributos[2] = forma.getText();
        java.sql.Date sql = new java.sql.Date(parsed.getTime());
        atributos[3] = sql;
        atributos[4] = llaveVendedor;
        atributos[5] = Integer.parseInt(llaveNumero);
        String query = "UPDATE DBO.VENTA SET IDVENDEDOR = ?, NUMERODEVENTA = ?,"
                    + " FORMADEPAGO = ?, FECHAVENTA = ? WHERE IDVENDEDOR = ? AND NUMERODEVENTA = ?";
        TablaDatos.executeUpdate(conexion, query, atributos);
        if(!abonado.getText().equals("") && !pendiente.getText().equals("")){
        atributos = new Object[7];
        atributos[0] = vendedor.getText();
        atributos[1] = Integer.parseInt(numero.getText()); 
        atributos[2] = sql;
        atributos[3] = Integer.parseInt(abonado.getText());
        atributos[4] = Integer.parseInt(pendiente.getText());
        atributos[5] = llaveVendedor;
        atributos[6] = Integer.parseInt(llaveNumero);
        query = "UPDATE DBO.PAGO SET IDVENDEDOR = ?, NUMERODEVENTA = ?,"
                    + " FECHADEPAGO = ?, MONTOABONADO = ?,MONTOPENDIENTE = ? WHERE IDVENDEDOR = ? AND NUMERODEVENTA = ?";
        TablaDatos.executeUpdate(conexion, query, atributos);
        }
       }catch(ParseException e){
           System.err.println("Error en fecha");
       }
       actualizar();
    }//GEN-LAST:event_aceptarActionPerformed

     private void actualizar() {
        try {
            function.run();
        } catch (Exception ex) {
            System.err.print("Error al retornar al padre");
        }
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField abonado;
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField fecha;
    private javax.swing.JTextField forma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pendiente;
    private javax.swing.JButton regresar;
    private javax.swing.JTextField vendedor;
    // End of variables declaration//GEN-END:variables
}
