/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.bases;

import java.util.Collections;

/**
 *
 * @author b22539
 */
public class ModificarCliente extends javax.swing.JFrame {

    final Runnable functionOnClose;

    /**
     * Creates new form ModificarCliente
     */
    public ModificarCliente(String[] TextFieldValues, Runnable functionOnClose) {
        this.functionOnClose = functionOnClose;
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        fieldNombre.setText(TextFieldValues[2]);
        fieldIdentificacion.setText(TextFieldValues[0]);
        fieldPrioridad.setText(TextFieldValues[1]);
    }

    public ModificarCliente(String[] TextFieldValues) {
        this(TextFieldValues, null);
    }

    public ModificarCliente() {
        this(Collections.nCopies(7, "").toArray(new String[7]), null);
    }

    private void returnToParent() {
        try {
            functionOnClose.run();
        } catch (Exception ex) {
            System.err.print("Error al retornar al padre");
        }
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labe = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        fieldIdentificacion = new javax.swing.JTextField();
        modificar = new javax.swing.JButton();
        fieldPrioridad = new javax.swing.JTextField();
        labelIdentificacion = new javax.swing.JLabel();
        labelPrioridad = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        verContacto = new javax.swing.JButton();
        labe1 = new javax.swing.JLabel();
        fieldNombre1 = new javax.swing.JTextField();

        labe.setText("Nombre:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });

        labelIdentificacion.setText("Identficación:");

        labelPrioridad.setText("Prioridad:");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        verContacto.setText("Ver contacto");
        verContacto.setActionCommand("verContacto");
        verContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verContactoActionPerformed(evt);
            }
        });

        labe1.setText("Nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIdentificacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelPrioridad, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldIdentificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(fieldPrioridad)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Regresar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(verContacto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(modificar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(labe1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldNombre1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdentificacion)
                    .addComponent(fieldIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrioridad)
                    .addComponent(fieldPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labe1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificar)
                    .addComponent(Regresar)
                    .addComponent(verContacto))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        returnToParent();
    }//GEN-LAST:event_modificarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        returnToParent();
    }//GEN-LAST:event_RegresarActionPerformed

    private void verContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verContactoActionPerformed
    }//GEN-LAST:event_verContactoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField fieldIdentificacion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldNombre1;
    private javax.swing.JTextField fieldPrioridad;
    private javax.swing.JLabel labe;
    private javax.swing.JLabel labe1;
    private javax.swing.JLabel labelIdentificacion;
    private javax.swing.JLabel labelPrioridad;
    private javax.swing.JButton modificar;
    private javax.swing.JButton verContacto;
    // End of variables declaration//GEN-END:variables
}
